-- ============================================================================
--  AniTrack · V11 站内通知（H2）
--
--  背景：站内此前**没有通知这个概念**。全仓只有一个聊天式的查询 —— 「谁回复了我」
--  （GET /api/user/received-replies），没有总数、没有分页、**没有已读状态**，而且点赞
--  侧连「谁赞了我」这一条都没有。用户看不到"有人对我说了什么"，也就没有任何理由回来。
--
--  这张表一次装上三种通知：REPLY(有人回复了我的评论) / REVIEW_LIKE(有人赞了我的评论)
--  / REPLY_LIKE(有人赞了我的回复)。**一张表 + type 列，不是三张表**：三者的收件人、
--  读/未读、排序、分页完全是同一套，切成三张的话未读计数要发三条 COUNT 再相加、列表
--  要三路归并排序、已读要三条 UPDATE —— 而这三件事正是这一页的全部逻辑。
--
--  为什么**这张表挂外键、而 V9 的账本一个都不挂**（两张表看着像，判断相反）：
--
--  · 账本记录的是**史料**，它必须活得比被记录的对象久 —— 删评论时把那一条处理记录
--    一起抹掉，恰恰是审计最不能接受的（见 V9 的说明）。
--  · 通知是**待办清单**，一条指向已删评论的通知没有任何意义，跟着消失才是对的。
--    所以 review_id / reply_id 挂 ON DELETE CASCADE。它同时办了两件事：语义正确，
--    以及孤儿行不会永久堆积（不挂外键就只剩"读的时候过滤掉"一途，而那样行还在表里、
--    索引还要扫）。
--  · 两级级联在这里是**现成的**：删评论 → (fk_review_reply_review, V8) 删回复 →
--    (fk_notification_reply, 本迁移) 删这些回复的通知；而指向那条评论本身的通知由
--    fk_notification_review 直接带走。V8 已经立过两级级联的先例，这里是同一个形状。
--
--  为什么 recipient_id / actor_id **不级联**：与 V7/V8 对 user_id 的规矩一致
--  （见 V8 里 fk_reply_like_user / fk_review_reply_user）。那条规矩的理由是"级联会
--  静默删掉子行、而计数器不跟着减"，这里没有计数器，但本仓目前根本没有删用户这条路，
--  所以这两列上的外键今天只是个数据完整性声明 —— 留着它，别顺手补 CASCADE。
--
--  为什么只建 (recipient_id, created_at) 一棵索引树：
--
--  · 列表分页要的是 recipient_id = ? ORDER BY created_at DESC —— 正是它；
--  · 未读计数要的是 recipient_id = ? AND read_at IS NULL。它没有自己的索引，是刻意的：
--    未读是一个**每次查看就清零**的小集合，最左前缀 recipient_id 已经把它收窄到"一个人
--    的几十行"，再往下走几步就够了。为它单独建 (recipient_id, read_at) 是给一棵会长大
--    的树付维护成本，换不到可观测的收益。
--
--  为什么用 read_at IS NULL 表示未读，而不是一个布尔列：一个字段同时回答"读没读"和
--  "什么时候读的"，而后者是"按已读时间排序""展示上次查看时间"唯一的来源。加了布尔列，
--  这两件事就再也补不回来了（只能再开一列时间，于是同一件事有两个真源）。
--
--  为什么 review_id 在三种类型上都写：读路径要拿 subjectId（跳番剧页）和评论摘要，
--  两个都得从 review 走。REPLY_LIKE 本可以只给 reply_id 让读路径拐一道 reply→review，
--  但那样三种类型就有两条不同的取数路径 —— 一条 JOIN FETCH、一条要 JOIN 两次。
--
--  为什么新开 V11 而不是改 V10：已执行过的迁移是历史，只能往后加（同 V1~V10）。
--
--  为什么这次两份脚本的语句逐字相同：与 V7~V10 同一判断 —— 用到的写法
--  (CREATE TABLE/INDEX IF NOT EXISTS、GENERATED BY DEFAULT AS IDENTITY、ON DELETE
--  CASCADE) 都是 H2 2.2 与 PostgreSQL 16 都认的。
--
--  与 postgres/V11__add_notifications.sql 一一对应（语句逐字相同，用例守着这一点）。
-- ============================================================================

CREATE TABLE IF NOT EXISTS notification (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    recipient_id BIGINT      NOT NULL,
    actor_id     BIGINT      NOT NULL,
    type         VARCHAR(16) NOT NULL,
    review_id    BIGINT,
    reply_id     BIGINT,
    read_at      TIMESTAMP(6),
    created_at   TIMESTAMP(6),
    CONSTRAINT pk_notification PRIMARY KEY (id),
    CONSTRAINT fk_notification_recipient FOREIGN KEY (recipient_id) REFERENCES "user" (id),
    CONSTRAINT fk_notification_actor FOREIGN KEY (actor_id) REFERENCES "user" (id),
    CONSTRAINT fk_notification_review FOREIGN KEY (review_id) REFERENCES review (id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_reply FOREIGN KEY (reply_id) REFERENCES review_reply (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_notification_recipient_created
    ON notification (recipient_id, created_at);
