-- ============================================================================
--  AniTrack · V1 基线建表（H2：开发与测试环境）
--
--  什么是「基线」：在引入 Flyway 之前，表是 Hibernate 用 ddl-auto=update 自己
--  建出来、自己改的。这个脚本就是那一刻的结构快照，用在**全新的空库**上
--  （比如新同事 clone 下来第一次启动），让库从零长得和实体类一致。
--
--  已有的库不会被这个脚本碰到：Flyway 配置了 baseline-on-migrate，
--  遇到「有表但没有迁移历史」的库只会记一条「已到 1」的基线，然后直接跑 V2
--  （V2 专门补老库缺的东西）。详见 README「设计要点 12」。
--
--  为什么 H2 和 PostgreSQL 各有一份，而不是写一份通用 SQL：
--  两个库确实都支持标准 SQL，但真正的差异都藏在细节里 —— 存文本的列在 H2 上
--  是无限长的 VARCHAR、在 PG 上是 text；自增在两边虽然都能写 IDENTITY 但
--  时间类型精度、注释与引号规则并不完全一致。与其写一份「两边都能跑但都别扭」
--  的脚本，不如各写一份老老实实的方言脚本。代价是每加一列要写两遍，
--  这一点由 MigrationScriptPairTest 钉住（两个目录的文件名与版本号必须成对）。
--
--  约定（写新脚本时请一起遵守）：
--    · 只用 DDL，不插任何业务数据。初始管理员由 DataInitializer 按配置创建。
--    · 约束与索引一律用可读名字（uk_ / fk_ / idx_ 前缀），不用 Hibernate 生成的
--      哈希名（如 UK_SB8BBOUER5WAK8VYIIY4PF2BX）。Hibernate 的 validate 只校验
--      表与列、不看约束名，所以改名是安全的；而可读名字在排障时值千金。
--    · "user" 是 SQL 保留字，两边都必须加引号 —— Hibernate 自己也是这么引的。
--    · 文本列故意不写长度：实体上没有长度上限，H2 的 VARCHAR 不写长度即为最长。
-- ============================================================================

-- 用户
CREATE TABLE "user" (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    username        VARCHAR(50)  NOT NULL,
    password        VARCHAR(255) NOT NULL,
    -- 唯一，但不加 NOT NULL：历史数据里存在空邮箱的行（引导账号创建时不经过注册接口）。
    -- SQL 标准里 UNIQUE 不约束 NULL，多个 NULL 可以共存。
    email           VARCHAR(100),
    avatar          VARCHAR(255),
    role            VARCHAR(10)  NOT NULL,
    status          VARCHAR(10)  NOT NULL,
    -- 连续登录失败次数 / 锁定截止时间，见 UserService.login 与 entity.User
    failed_attempts INTEGER,
    locked_until    TIMESTAMP(6),
    created_at      TIMESTAMP(6),
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uk_user_username UNIQUE (username),
    CONSTRAINT uk_user_email UNIQUE (email)
);

-- 番剧。id 不加 IDENTITY：这个 id 就是 Bangumi 的 subject id（外部数据自带主键），
-- 由同步逻辑写入，而不是由数据库生成。
CREATE TABLE anime (
    id               INTEGER      NOT NULL,
    title            VARCHAR(200) NOT NULL,
    title_cn         VARCHAR(200),
    cover_url        VARCHAR(500),
    summary          VARCHAR,
    rating           NUMERIC(3, 1),
    rating_count     INTEGER,
    sort_rank        INTEGER,
    total_episodes   INTEGER,
    date             VARCHAR(20),
    season           VARCHAR(30),
    status           VARCHAR(20),
    platform         VARCHAR(50),
    tags             VARCHAR(500),
    cache_updated_at TIMESTAMP(6),
    CONSTRAINT pk_anime PRIMARY KEY (id)
);

-- 标签
CREATE TABLE tag (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT pk_tag PRIMARY KEY (id),
    CONSTRAINT uk_tag_name UNIQUE (name)
);

-- 番剧与标签的多对多。tag_id 有外键；anime_id 刻意没有 —— 见 entity.AnimeTag 的说明。
CREATE TABLE anime_tag (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    anime_id INTEGER NOT NULL,
    tag_id   BIGINT  NOT NULL,
    CONSTRAINT pk_anime_tag PRIMARY KEY (id),
    CONSTRAINT fk_anime_tag_tag FOREIGN KEY (tag_id) REFERENCES tag (id)
);
CREATE INDEX idx_animetag_anime ON anime_tag (anime_id);
CREATE INDEX idx_animetag_tag ON anime_tag (tag_id);

-- 剧集。id 同样来自 Bangumi，不自增。
CREATE TABLE episode (
    id               BIGINT NOT NULL,
    anime_id         INTEGER NOT NULL,
    episode_num      INTEGER NOT NULL,
    title            VARCHAR(200),
    airdate          VARCHAR(20),
    duration         VARCHAR(10),
    cache_updated_at TIMESTAMP(6),
    CONSTRAINT pk_episode PRIMARY KEY (id),
    CONSTRAINT fk_episode_anime FOREIGN KEY (anime_id) REFERENCES anime (id)
);

-- 追番记录。subject_id 指向 Bangumi 的番剧 id（不是本地 anime.id），所以没有外键。
CREATE TABLE anime_tracking (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT      NOT NULL,
    subject_id INTEGER     NOT NULL,
    status     VARCHAR(20) NOT NULL,
    progress   INTEGER     NOT NULL,
    score      INTEGER,
    notes      VARCHAR,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT pk_anime_tracking PRIMARY KEY (id),
    CONSTRAINT fk_anime_tracking_user FOREIGN KEY (user_id) REFERENCES "user" (id)
);

-- 看过的剧集（打勾）
CREATE TABLE episode_watched (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT  NOT NULL,
    anime_id    INTEGER NOT NULL,
    episode_num INTEGER NOT NULL,
    watched_at  TIMESTAMP(6),
    CONSTRAINT pk_episode_watched PRIMARY KEY (id),
    CONSTRAINT fk_episode_watched_user FOREIGN KEY (user_id) REFERENCES "user" (id)
);

-- 短评。subject_id 同样指向 Bangumi。
CREATE TABLE review (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT  NOT NULL,
    subject_id INTEGER NOT NULL,
    rating     INTEGER NOT NULL,
    content    VARCHAR,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT pk_review PRIMARY KEY (id),
    CONSTRAINT fk_review_user FOREIGN KEY (user_id) REFERENCES "user" (id)
);

-- AI 助手的会话与消息
CREATE TABLE agent_conversation (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT      NOT NULL,
    title         VARCHAR(60),
    persona       VARCHAR(32) NOT NULL,
    message_count INTEGER     NOT NULL,
    created_at    TIMESTAMP(6),
    updated_at    TIMESTAMP(6),
    CONSTRAINT pk_agent_conversation PRIMARY KEY (id),
    CONSTRAINT fk_agent_conversation_user FOREIGN KEY (user_id) REFERENCES "user" (id)
);

CREATE TABLE agent_message (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    conversation_id BIGINT      NOT NULL,
    role            VARCHAR(16) NOT NULL,
    content         VARCHAR,
    created_at      TIMESTAMP(6),
    CONSTRAINT pk_agent_message PRIMARY KEY (id),
    CONSTRAINT fk_agent_message_conversation FOREIGN KEY (conversation_id) REFERENCES agent_conversation (id)
);
