-- ============================================================================
--  AniTrack · V8 给短评加「回复」（H2）
--
--  背景：V7 让评论可以被赞，这一版让它可以被回。回复**扁平一层** —— 所有回复平铺在
--  评论下，不能再回复回复，表里因此没有 parent_id。
--
--  为什么扁平：这是拍过板的选择。有了 parent_id 就要递归查询、树形渲染、以及
--  「回复 @ 某人」的语义，而那三样正是移动端最难做好的东西；换来的收益（楼中楼）
--  在一屏只有几条评论的详情页上并不成立。真要做嵌套的时候再迁移，比现在先建一棵
--  永远用不满的树便宜。
--
--  为什么是三样东西（review 加一列 reply_count + 一张 review_reply + 一张 reply_like）：
--
--  · review_reply 是回复本身，这条没有替代品。
--  · reply_count 的理由与 V7 的 like_count 逐字相同：列表里每条评论要显示「N 条回复」，
--    靠 LEFT JOIN + COUNT 现场聚合的话，它要和「JOIN FETCH r.user + Pageable」共存 ——
--    那个组合会让 Hibernate 把整个结果集读进内存再切页，返回值看着对，只是分页不再是
--    库做的。代价同样是计数可能与行数漂移，防法也相同：这一列只有**一个**写入路径
--    （ReviewRepository.increment/decrementReplyCount 的 JPQL UPDATE），JPA 那一侧
--    连碰都碰不到（Review.replyCount 标了 insertable=false, updatable=false）。
--  · reply_like 与 review_reply.like_count：回复**也能被赞**，这是拍板的一部分。
--    机制与评论的赞完全一样（一行 = 一次赞，计数列是行数的冗余副本），所以这里不
--    重复解释，理由见 V7。
--
--  为什么 review_reply 上要建 (review_id, created_at) 索引，而 V7 的 review_like 上
--  什么都不建 —— 两处判断不矛盾：
--
--  · review_like 上有一条唯一约束 uk_review_like_review_user (review_id, user_id)，
--    它的最左前缀 review_id 已经服务了「谁赞了这条」。再建是纯写放大。
--  · review_reply 上**没有**任何唯一约束（同一个人在同一条评论下可以回任意多条），
--    也就没有任何现成的树可借；而「这条评论下的回复」正是这一版最主要的读路径。
--    所以这一棵是必须的，不是顺手加的。
--
--  为什么外键上的 ON DELETE CASCADE 只给父行、不给 user_id（与 V7 同一条规矩）：
--
--  · review_reply.review_id → review(id) 级联：删评论要带走它的回复。删评论有三条
--    路径（ReviewService.deleteReview、AdminService.deleteAnyReview、测试里的裸
--    DELETE FROM review），不级联的话每一条都会撞 RESTRICT 而失败。
--  · reply_like.reply_id → review_reply(id) 级联：删回复要带走它的赞。于是这里出现
--    了**两级**级联（删评论 → 删回复 → 删回复的赞），H2 与 PG 都支持。
--  · user_id 一律不级联，理由同 V7：用户删除路径将来出现时，库级联会静默删掉子行而
--    计数不跟着减，且没有任何东西会报错。
--
--  为什么 content 是 NOT NULL，而 review.content 可空 —— 这不是笔误，两者是不同的东西：
--  · 评论是「评分 + 可选文字」，只打分不写字是合法用法（详情页上显示成「（无文字）」）。
--  · 回复**只有**文字。一条空回复没有任何含义，允许它进去只会让列表里多出一行空白。
--    接口层是 @NotBlank，这里是最终那道防线（同 README 设计要点 11 的口径）。
--
--  为什么两列的默认值都要写 IF NOT EXISTS + DEFAULT：这份脚本在一台「Flyway 之前就
--  存在的老库」上也会被执行到，它可能因为历史上手工建过而已经存在；另外
--  「列默认值」在 ddl-auto=create-drop 的那几个测试里还要再写一遍（实体上的
--  columnDefinition），因为那些测试用的是实体生成出来的表，根本不跑迁移。
--
--  为什么新开 V8 而不是改 V7：已执行过的迁移是历史，只能往后加（同 V1~V7）。
--
--  为什么这次两份脚本的语句逐字相同：与 V7 同一判断 —— 用到的写法
--  (ADD COLUMN IF NOT EXISTS、CREATE TABLE/INDEX IF NOT EXISTS、GENERATED BY DEFAULT
--  AS IDENTITY、ON DELETE CASCADE) 都是 H2 2.2 与 PostgreSQL 16 都认的。
--
--  与 postgres/V8__add_review_replies.sql 一一对应（语句逐字相同，用例守着这一点）。
-- ============================================================================

ALTER TABLE review ADD COLUMN IF NOT EXISTS reply_count BIGINT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS review_reply (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    review_id  BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    content    VARCHAR NOT NULL,
    like_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT pk_review_reply PRIMARY KEY (id),
    CONSTRAINT fk_review_reply_review FOREIGN KEY (review_id) REFERENCES review (id) ON DELETE CASCADE,
    CONSTRAINT fk_review_reply_user FOREIGN KEY (user_id) REFERENCES "user" (id)
);

-- 「这条评论下的回复」是这一版最主要的读路径；并列时按 id 兜底（created_at 可空，
-- 而 ORDER BY 里 NULL 排哪两个库不一致，见 ReviewQueries 的说明）。
CREATE INDEX IF NOT EXISTS idx_review_reply_review_created
    ON review_reply (review_id, created_at);

CREATE TABLE IF NOT EXISTS reply_like (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    reply_id   BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    CONSTRAINT pk_reply_like PRIMARY KEY (id),
    CONSTRAINT uk_reply_like_reply_user UNIQUE (reply_id, user_id),
    CONSTRAINT fk_reply_like_reply FOREIGN KEY (reply_id) REFERENCES review_reply (id) ON DELETE CASCADE,
    CONSTRAINT fk_reply_like_user FOREIGN KEY (user_id) REFERENCES "user" (id)
);
