-- ============================================================================
--  AniTrack · V9 管理端操作账本（H2）
--
--  背景：管理端有四个破坏性动作 —— 封禁/启用用户、改角色、解锁定、删评论 —— 它们
--  此前**零留痕**：AdminService 里没有一行日志，库里没有一张审计表。其中「改角色」
--  能把任何人提成管理员，而事后没有任何人能查出是谁、在什么时候、对谁做的。
--
--  为什么是一张通用表，而不是照「评论管理」切一张专用表：
--
--  · 四个动作的记录形状是同一个 —— 谁、在什么时候、对什么东西、做了什么。切成两张
--    专用表的话，管理端就有两本账、要翻两个地方，而「改角色提权」这条最该被查的
--    路径恰恰会落在没人翻的那本上。
--  · 各动作特有的细节（角色从什么改成什么、被删评论的正文）进 detail 列，而不是给
--    每个动作加一列 —— 那样加第五个动作就要再来一轮迁移。
--
--  为什么**一个外键都不挂**（全 schema 唯一一张这样的表）：
--
--  · 账本记录的是**已经发生过的事实**，而事实里的东西将来可能不存在。target_id 挂
--    CASCADE 等于「删评论时把它的处理记录一起抹掉」——那正是账本最该留下的那一条；
--    不挂 CASCADE 就是 RESTRICT，会让一次正常的删除撞上一个与它毫不相干的约束错误。
--    actor_id 同理。
--  · 顺带一提，target_id 指向哪张表由 target_type 决定，这种多态引用在数据库层本来
--    就建不出外键。
--  · 代价：它拦不住写进一个不存在的 id。兜底的是「唯一的写入者在 AdminService 里，
--    且与动作本身同一个事务」（见 AdminService.record 的注释）。
--
--  为什么 actor_name 是快照列而不是 join 出来的：actor 改名或账号被删之后，账本仍然
--  要读得懂。只存 id 的话，一次改名就把历史记录变成了几个认不出来的数字。
--
--  为什么只建 (created_at) 索引、**不建** (actor_id)：
--
--  · 这一页唯一的排序是时间倒序，idx_admin_action_log_created 够用；
--  · 管理端就一个管理员，按人筛是伪需求。将来真要按 actor 筛，该建的是
--    (actor_id, created_at) 而不是 (actor_id) —— 与 V4 末尾给 review 留的那条注记
--    同一个道理：过滤字段在前、排序字段在后，单独的前缀索引服务不了排序。
--
--  为什么 detail 用无长度 VARCHAR：H2 是 varchar、PG 是 text，与 review.content 同一个
--  写法。它存的是**人类可读的一句话**，不是给程序解析的 JSON —— 审计要回答的是「谁在
--  什么时候对谁做了什么」，不是给下游喂数据。
--
--  为什么新开 V9 而不是改 V8：已执行过的迁移是历史，只能往后加（同 V1~V8）。
--
--  为什么这次两份脚本的语句逐字相同：与 V7/V8 同一判断 —— 用到的写法
--  (CREATE TABLE/INDEX IF NOT EXISTS、GENERATED BY DEFAULT AS IDENTITY) 都是
--  H2 2.2 与 PostgreSQL 16 都认的。
--
--  与 postgres/V9__add_admin_action_log.sql 一一对应（语句逐字相同，用例守着这一点）。
-- ============================================================================

CREATE TABLE IF NOT EXISTS admin_action_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    actor_id    BIGINT      NOT NULL,
    actor_name  VARCHAR(50) NOT NULL,
    action      VARCHAR(32) NOT NULL,
    target_type VARCHAR(16) NOT NULL,
    target_id   BIGINT      NOT NULL,
    detail      VARCHAR,
    created_at  TIMESTAMP(6),
    CONSTRAINT pk_admin_action_log PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_admin_action_log_created
    ON admin_action_log (created_at);
