-- ============================================================================
--  AniTrack · V13 评论举报（PostgreSQL）
--
--  背景：评论区能点赞、能回复、能删除，唯独**没有「这条有问题」这个出口**。用户看到
--  一条广告或一句辱骂，能做的只有无视 —— 而管理员那一侧也就永远不知道哪条评论需要
--  看一眼。这一版把举报这件事变成一行数据，并给管理端的评论列表加一个「只看待处理」
--  的筛选。
--
--  为什么是单独一张表，而不是给 review 加一个 report_count 列：
--
--  · 计数答不了「谁举报的、为什么、什么时候」—— 而处理一条举报要的正是这三样；
--  · 更要紧的是**一人一条评论只能举报一次**（见下面那条唯一约束）。只有计数列的话，
--    这个规矩没有任何东西守着，一个人点十次就是十次。
--
--  四个不能想当然的地方：
--
--  1. uk_review_report_review_reporter 是「一人对一条评论只能举报一次」。
--     没有它，一个人可以刷一百条举报，「待处理」这个数立刻失去意义 —— 这正是举报
--     轰炸最经典的入口。有了它，重复举报退化成**幂等**（回 200 而不是报错），
--     与点赞那条路同一种处理方式。
--
--     顺带它还是一棵树：最左前缀 review_id 服务的正是「这条评论被举报了几次」
--     （管理端一页 20 行的那次批量聚合）。所以**不另建索引** —— 理由与 V7 的
--     review_like 逐字相同（唯一约束自带索引，再建一个是纯粹的写放大），
--     这也顺带让 V4 那条「review 表上恰好只有 IDX_REVIEW_SUBJECT_CREATED」的硬断言
--     原样成立（新表加索引不影响它）。
--
--     注意这条唯一约束**不带 status**：一个人撤回不了自己的举报，重复举报也不会
--     因为「上一条已经被忽略了」而重新计一次。要重新举报，得先有人把它删掉 ——
--     这是刻意的，否则「忽略」就变成了「请你再点一次」。
--
--  2. reason 是白名单四值：SPAM(垃圾广告) / ABUSE(辱骂攻击) / SPOILER(剧透) /
--     OTHER(其他)。**写接口上未知值回 400**，而读接口（管理端按 reason 筛）对未知值
--     沉默放行 —— 这个不对称是本仓既有的一条 doctrine，写与读各有一处注释讲它
--     （AdminService 里 setUserRole 与 getUserPage 那两段）。举报是**写**：写错一个
--     理由值意味着这条举报落进一个谁也筛不出来的档位，而且事后补不回来。
--
--  3. status 只有两个值：PENDING / DISMISSED。**没有 RESOLVED** —— 「评论已被删除」
--     这件事不靠改状态表达，靠**查询条件**表达（待处理 = status='PENDING' 且它的
--     评论还在）。这样就不存在「删了又恢复，举报状态该不该退回去」这种循环状态机：
--     恢复评论之后那条举报**自动**回到队列里，一次回写都不需要。
--
--  4. ON DELETE CASCADE 只给 review_id，不给 reporter_id / handled_by ——
--     与 V7/V8 对 user_id 的规矩一致：用户目前没有删除路径，将来有的时候库级联会
--     静默删掉这些行而没有任何东西会报错。review_id 则必须级联：删评论有三条路径
--     （ReviewService.deleteReview、AdminService.deleteAnyReview、测试里的裸 DELETE），
--     不级联的话每一条都会撞 RESTRICT 而失败，等于把「删除评论」直接弄坏。
--
--     review 将来改成**软删**之后这条级联就再不会触发 —— 但仍然要留着：三条删除
--     路径里任一条哪天被改回硬删，没有它就会撞上一个无法理解的约束错误。
--
--  为什么新开 V13 而不是改前面的：已执行过的迁移是历史，Flyway 记着校验和，
--  改动其中任何一个字节都会让下次启动直接拒绝。只能往后加。
--
--  为什么这次两份脚本逐字相同：CREATE TABLE IF NOT EXISTS、GENERATED BY DEFAULT AS
--  IDENTITY、内联 CONSTRAINT ... UNIQUE / FOREIGN KEY ... ON DELETE CASCADE，
--  都是 H2 2.2 与 PostgreSQL 16 都认的写法 —— 与 V4/V5/V7/V8/V12 同一判断。
--
--  PostgreSQL 侧的两点补充（都只是「为什么不必额外做什么」，语句本身与 H2 那份逐字相同）：
--
--  · 这条唯一约束在 PG 上同样自带一棵 B 树，最左前缀 review_id 服务「这条评论被
--    举报了几次」，不需要另建索引 —— 与 H2 那边同一条理由。
--  · ON DELETE CASCADE 在 PG 上是行级触发器，删一条评论会去 review_report 里
--    按 review_id 探针（走上面那棵树的左前缀），量级与 H2 一致。
--
--  与 h2/V13__add_review_reports.sql 一一对应（语句逐字相同，用例守着这一点）。
-- ============================================================================

CREATE TABLE IF NOT EXISTS review_report (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    review_id   BIGINT NOT NULL,
    reporter_id BIGINT NOT NULL,
    reason      VARCHAR(32) NOT NULL,
    detail      VARCHAR(500),
    status      VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    handled_by  BIGINT,
    handled_at  TIMESTAMP(6),
    created_at  TIMESTAMP(6),
    CONSTRAINT pk_review_report PRIMARY KEY (id),
    CONSTRAINT uk_review_report_review_reporter UNIQUE (review_id, reporter_id),
    CONSTRAINT fk_review_report_review   FOREIGN KEY (review_id)   REFERENCES review (id) ON DELETE CASCADE,
    CONSTRAINT fk_review_report_reporter FOREIGN KEY (reporter_id) REFERENCES "user" (id),
    CONSTRAINT fk_review_report_handler  FOREIGN KEY (handled_by)  REFERENCES "user" (id)
);
