-- ============================================================================
--  AniTrack · V14 评论软删（PostgreSQL）
--
--  背景：管理端删评论此前是**硬删**（一条 DELETE FROM review），而它是管理端几个
--  破坏性动作里唯一一个**不可逆**的 —— 封禁能解、角色能改回来、锁能解、密码能重置，
--  唯独删掉的评论连正文都找不回来。管理员点错一行，或者事后发现那条评论其实不该删，
--  唯一的补救是请作者重写一遍。
--
--  这一版把「删」改成打一个时间戳：评论从用户侧消失（所有读路径都带上
--  deleted_at IS NULL），但行还在，管理端能恢复，账本里那条 REVIEW_DELETE 也不再是
--  一条指向虚空的记录。
--
--  三个不能想当然的地方：
--
--  1. 本轮**只加了列，没有加索引** —— 这是刻意的，不是漏了。
--     热路径（某部番的评论列表）走的是 IDX_REVIEW_SUBJECT_CREATED，条件里多一个
--     deleted_at IS NULL 只是对已经命中的行多做一次判断；被删的行是极少数，
--     为它单独建一个索引换不来什么，却是实打实的写放大。更要紧的是
--     HotPathIndexMigrationTest 里有一条硬断言：「review 表上恰好只有那一个 IDX_ 索引」
--     —— 那条断言本身就是用来拦「顺手加索引」的，别把它改成白名单。
--
--  2. deleted_by 可空、无默认值，**而且它和 deleted_at 必须同时有值或同时为空**。
--     两个各自可空的列表达一件事，本来就有半截状态的风险；这里靠**只有一条写入
--     路径**（AdminService.deleteAnyReview 与 restoreAnyReview，各自在同一个事务里
--     一起写）保证，而不是靠约束 —— 全 schema 都没有 CHECK 的惯例，而且半截状态
--     一旦出现，读路径看到的是「有删除时间但没有删除人」，界面上表现为「已移除
--     （未知）」这种既不报错也说不清的格子。
--
--  3. 外键不给 ON DELETE CASCADE，与 V7/V8 对 user_id 的规矩一致。
--     这里尤其要守：deleted_by 记的是「谁把它撤下来的」，而那个人被删号之后，
--     这一列应该继续指向一个已经不存在的 id（它是一个**事实**），而不是把整条评论
--     连带抹掉。级联在这里没有任何正确解释。
--
--  为什么可空、无默认值能用 ADD COLUMN：与 V10 的 password_changed_at 同一条理由 ——
--  给已有表加 NOT NULL 列，H2 与 PostgreSQL 都会因为没有 DEFAULT 子句而拒绝执行。
--  语义上也正好：NULL 读作「在架上」，存量行一行都不用改就是对的。
--
--  ⚠️ 为什么外键写成**列级具名约束**（BIGINT CONSTRAINT fk_... REFERENCES ...），
--  而不是另起一句 ALTER TABLE ... ADD CONSTRAINT：
--
--     `ALTER TABLE ... ADD CONSTRAINT` 在 PostgreSQL 上**没有 IF NOT EXISTS**
--     （V3 那一段注释记的就是这件事，那边只好给 PG 单独套一个 DO 匿名块）。
--     这一版要同时守住两条本仓的不变量 —— 「两方言语句逐字相同」（V4 起每一条迁移
--     都有一条用例在断）和「每一步都能重复执行」（V2 立下的规矩）。写成列级具名约束
--     就两条都守住了：它跟着 ADD COLUMN 的 IF NOT EXISTS 一起被跳过，重跑一次是
--     彻底的空操作，而且约束名仍然是显式的（不是库自动生成的那个猜不出来的名字）。
--     本机用项目实际用的 h2-2.2.224.jar 实测过：连跑两遍无错，约束名就是
--     FK_REVIEW_DELETED_BY。
--
--     代价说清楚：列已存在而约束缺失时（手工改过库、或者这段脚本被拆开执行过），
--     这一句会**静默跳过**，约束就永远不会被补上。这与所有 IF NOT EXISTS 是同一个
--     性质，不是这一句独有的问题。
--
--      PostgreSQL 侧补一句：列级具名约束在 PG 上是标准写法（column_constraint 的语法
--      里就有 `[ CONSTRAINT name ] REFERENCES reftable [ (refcolumn) ]`），但**本机
--      没跑过真 PG** —— 上面那句实测只覆盖 H2。PG 侧的证据只有 CI 的「镜像 + compose
--      冒烟」那一步（真 PG 上跑 Flyway），那是本仓唯一能验 PG 迁移的地方。
--
--  为什么新开 V14 而不是改 V13：已执行过的迁移是历史，Flyway 记着校验和，
--  改动其中任何一个字节都会让下次启动直接拒绝。只能往后加。
--
--  与 h2/V14__add_review_soft_delete.sql 一一对应（语句逐字相同，用例守着这一点）。
--  V13 的注释里已经预告过这一版（「review 将来改成软删之后那条级联就再不会触发，
--  但仍然要留着」）—— 那条级联确实留着，它守的是硬删那三条路径。
-- ============================================================================

ALTER TABLE review ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP(6);

ALTER TABLE review ADD COLUMN IF NOT EXISTS deleted_by BIGINT
    CONSTRAINT fk_review_deleted_by REFERENCES "user" (id);
