-- ============================================================================
--  AniTrack · V17 「角色、制作人员、关联条目」(PostgreSQL)
--
--  背景：详情页此前只有简介、剧集、标签、评论。上游其实还有三份现成的附属数据
--  （GET /v0/subjects/{id}/characters | persons | subjects），匿名可读、单次返回
--  整个集合，我们一条都没取过。这一版把这三份落到本地。
--
--  为什么是**五张表**（一张状态表 + 四张内容表）：
--
--  · 三份数据各自的形状完全不同（角色带声优、人员带职务、关联条目带方向），
--    塞进一张"万能附属表"就是四列全可空 + 一个 section 字符串，读的时候谁都看不懂。
--  · 声优**必须单独一张表**，不能像 anime.tags 那样用 CSV 拼一列：tags 用 CSV 的前提是
--    "40127 个标签一个都不含逗号"（有实测），而人名没有这个前提 —— 实测一个关联作品名里
--    就带着分号（コードギアス Genesic Re;CODE）。而且角色→声优是一对多（实测 128 条角色里
--    63 条没有声优、最多 2 个），CSV 会把"没有"与"有一个空名"变得分不出来。
--
--  为什么标记列是**可空时间戳**，不是计数器：
--
--  · 计数器（characters_count 之类）是第二份事实来源，它会与内容表的实际行数漂移，
--    而漂移不报错 —— 删了一半的行、计数器还写着 128，没有任何地方会红。
--  · 时间戳还额外带得出新鲜度，而"什么时候取的"正是下面那条 TTL 需要的东西。
--  · NULL 与"有值"是一对干净的判据：NULL = 从没取过 / 取到过但没取全；非 NULL =
--    某个时刻完整取回过。半批不落库这条规矩（见 SubjectExtrasWriter）靠的就是它。
--
--  为什么 TTL 是必须的（时间戳而不是"取过就永远算数"）：
--
--  · 新季度会加角色、补录人员、新关联条目上线。marker 一落永不重取，等于把
--    "首播那天的角色表"永久固化。TTL 见 anitrack.subject-extras.ttl（默认 24h），
--    三个 section 各自可覆盖。
--
--  为什么是**三列**而不是 (subject_id, section) 两列：
--
--  · 后者把 section 变成一个字符串，而字符串写错不会编译失败 —— `character` 与
--    `characters` 只差一个字母，拼错之后读路径永远查不到 marker，于是每次打开详情页
--    都重取一遍上游，且没有任何症状（没有异常、没有慢查询、日志一片正常）。
--    三列之后，拼错是一个编译错误。
--
--  为什么**一个外键都没有**：
--
--  · 与 login_event.user_id 同一条理由：这三个请求与 /api/bangumi/subject/{id} 是
--    并行发的（前端 allSettled），写这张表时 anime 那一行完全可能还不存在 ——
--    挂上外键就是把一个正常的并发顺序变成一次插入失败。
--  · 反过来说，附属数据的存在也不该被条目的存在绑住：删掉一个条目，它的角色表
--    留下来仍然是一条真实的上游快照，没有任何害处。
--
--  为什么四张内容表一律用**代理主键**，而不是照抄 episode 的自然键：
--
--  · 实测：/v0/subjects/8/persons 里同一个 person 以不同职务出现 5 次（person 419）；
--    /v0/subjects/253/persons 里 95767|助理制片人 原样出现两遍（名字也相同）；
--    声优那边更彻底 —— **上游的 actor 元素根本没有 relation 字段**（实测 0 条有），
--    同一个 actor_id 在一个条目里最多重复 4 次（同一个人配了不同角色）。
--    所以 (person_id, relation)、(subject_id, person_id) 甚至 (character_id, actor_id)
--    都不唯一，建唯一约束的结果是**整批插入失败**，而失败被 catch 住之后表现为
--    "这块永远是空的"。
--  · 代理键 + 完整回源时 delete-then-insert，正好对上"上游给什么就是什么"这个语义：
--    本地不需要判断哪条该更新、哪条是新来的。
--
--  为什么每张表都有一个 sort_order：
--
--  · delete-then-insert 之后，"行的物理顺序"不再是上游给的顺序，而 SELECT 不带
--    ORDER BY 时数据库返回的顺序**没有任何保证**（小表上碰巧是插入序，一旦走了别的
--    索引就变了）。而角色的排列顺序是有意义的：主角不该排在闲角后面。
--  · 存下来而不是读的时候重排：relation 的取值有四种（主角/配角/闲角/旁白），
--    按它们排是"我们编的一个序"，而上游给的是一个确定的序 —— 抄它的，别猜。
--
--  为什么都是带长度的 VARCHAR(n)：
--
--  · 与 V9 的 detail 不同，这些列**不需要**无限长（它们是从上游字段抄过来的短串），
--    而带长度能在写坏的时候当场报错。长度的取法：实测六部番的字段最长值
--    （角色名 28、人员名 26、关联条目名 58、职务 8、定位 2）之后取了一个几倍的余量，
--    剩下的交给 mapper 里的 cap() 截断 —— 整批一个事务，任何一行超长都会让
--    **全部**回滚，marker 不写，下次再取，再失败，这块从此永远空着。
--    image 列要装得下 /api/img?url=… 那种百分号编码后的长地址，所以给到 500。
--
--  为什么用 ADD ... IF NOT EXISTS / CREATE ... IF NOT EXISTS：V2 立下的规矩 ——
--  每一步都必须可重复执行。
--
--  与 h2/V17__add_subject_extras.sql 一一对应（语句逐字相同，用例守着这一点）。
-- ============================================================================

CREATE TABLE IF NOT EXISTS subject_extras (
    subject_id            INTEGER,
    characters_fetched_at TIMESTAMP(6),
    staff_fetched_at      TIMESTAMP(6),
    relations_fetched_at  TIMESTAMP(6),
    CONSTRAINT pk_subject_extras PRIMARY KEY (subject_id)
);

CREATE TABLE IF NOT EXISTS subject_character (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    subject_id   INTEGER      NOT NULL,
    character_id INTEGER      NOT NULL,
    name         VARCHAR(200) NOT NULL,
    relation     VARCHAR(32),
    image        VARCHAR(500),
    sort_order   INTEGER      NOT NULL,
    CONSTRAINT pk_subject_character PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_subject_character_subject
    ON subject_character (subject_id);

CREATE TABLE IF NOT EXISTS subject_character_actor (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    subject_id   INTEGER      NOT NULL,
    character_id INTEGER      NOT NULL,
    actor_id     INTEGER      NOT NULL,
    name         VARCHAR(200) NOT NULL,
    image        VARCHAR(500),
    sort_order   INTEGER      NOT NULL,
    CONSTRAINT pk_subject_character_actor PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_subject_character_actor_subject
    ON subject_character_actor (subject_id);

CREATE TABLE IF NOT EXISTS subject_staff (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    subject_id INTEGER      NOT NULL,
    person_id  INTEGER      NOT NULL,
    name       VARCHAR(200) NOT NULL,
    relation   VARCHAR(32),
    image      VARCHAR(500),
    sort_order INTEGER      NOT NULL,
    CONSTRAINT pk_subject_staff PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_subject_staff_subject
    ON subject_staff (subject_id);

CREATE TABLE IF NOT EXISTS subject_relation (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    subject_id INTEGER      NOT NULL,
    related_id INTEGER      NOT NULL,
    name       VARCHAR(200),
    name_cn    VARCHAR(200),
    relation   VARCHAR(32),
    image      VARCHAR(500),
    sort_order INTEGER      NOT NULL,
    CONSTRAINT pk_subject_relation PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_subject_relation_subject
    ON subject_relation (subject_id);
