-- ============================================================================
--  AniTrack · V1 基线建表（PostgreSQL：生产环境）
--
--  与 h2/V1__init_schema.sql 一一对应（版本号、表、列、约束名都相同，只有方言不同）。
--  改结构时请两份一起改，MigrationScriptPairTest 会检查两个目录的文件名成对。
--
--  关于「已有的库」：Flyway 配了 baseline-on-migrate，遇到有表但没有迁移历史的
--  库不会执行这个脚本，只记一条「已到 1」的基线，然后跑 V2 补差异。
--  所以这里可以放心地写「全新安装应该是什么样」。
--
--  方言说明：
--    · 自增用标准的 GENERATED BY DEFAULT AS IDENTITY，而不是历史的 serial ——
--      serial 是 PostgreSQL 的旧写法（会额外建一个序列并把列默认值指过去），
--      标准写法语义一样、更清楚，也是官方现在推荐的。BY DEFAULT（而非 ALWAYS）
--      意味着仍然允许显式插入 id，保留一点回旋余地。
--    · 长文本用 text（H2 那边是无限长的 VARCHAR）。
--    · 时间统一 timestamp(6) without time zone，与 LocalDateTime 对齐。
--    · "user" 是保留字，必须加双引号。
-- ============================================================================

-- 用户
CREATE TABLE "user" (
    id              bigint       GENERATED BY DEFAULT AS IDENTITY,
    username        varchar(50)  NOT NULL,
    password        varchar(255) NOT NULL,
    -- 唯一，但不加 NOT NULL：历史数据里存在空邮箱的行（引导账号创建时不经过注册接口）。
    -- SQL 标准里 UNIQUE 不约束 NULL，多个 NULL 可以共存。
    email           varchar(100),
    avatar          varchar(255),
    role            varchar(10)  NOT NULL,
    status          varchar(10)  NOT NULL,
    -- 连续登录失败次数 / 锁定截止时间，见 UserService.login 与 entity.User
    failed_attempts integer,
    locked_until    timestamp(6),
    created_at      timestamp(6),
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uk_user_username UNIQUE (username),
    CONSTRAINT uk_user_email UNIQUE (email)
);

-- 番剧。id 不加 IDENTITY：这个 id 就是 Bangumi 的 subject id（外部数据自带主键），
-- 由同步逻辑写入，而不是由数据库生成。
CREATE TABLE anime (
    id               integer      NOT NULL,
    title            varchar(200) NOT NULL,
    title_cn         varchar(200),
    cover_url        varchar(500),
    summary          text,
    rating           numeric(3, 1),
    rating_count     integer,
    sort_rank        integer,
    total_episodes   integer,
    date             varchar(20),
    season           varchar(30),
    status           varchar(20),
    platform         varchar(50),
    tags             varchar(500),
    cache_updated_at timestamp(6),
    CONSTRAINT pk_anime PRIMARY KEY (id)
);

-- 标签
CREATE TABLE tag (
    id   bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    CONSTRAINT pk_tag PRIMARY KEY (id),
    CONSTRAINT uk_tag_name UNIQUE (name)
);

-- 番剧与标签的多对多。tag_id 有外键；anime_id 刻意没有 —— 见 entity.AnimeTag 的说明。
CREATE TABLE anime_tag (
    id       bigint  GENERATED BY DEFAULT AS IDENTITY,
    anime_id integer NOT NULL,
    tag_id   bigint  NOT NULL,
    CONSTRAINT pk_anime_tag PRIMARY KEY (id),
    CONSTRAINT fk_anime_tag_tag FOREIGN KEY (tag_id) REFERENCES tag (id)
);
CREATE INDEX idx_animetag_anime ON anime_tag (anime_id);
CREATE INDEX idx_animetag_tag ON anime_tag (tag_id);

-- 剧集。id 同样来自 Bangumi，不自增。
CREATE TABLE episode (
    id               bigint       NOT NULL,
    anime_id         integer      NOT NULL,
    episode_num      integer      NOT NULL,
    title            varchar(200),
    airdate          varchar(20),
    duration         varchar(10),
    cache_updated_at timestamp(6),
    CONSTRAINT pk_episode PRIMARY KEY (id),
    CONSTRAINT fk_episode_anime FOREIGN KEY (anime_id) REFERENCES anime (id)
);

-- 追番记录。subject_id 指向 Bangumi 的番剧 id（不是本地 anime.id），所以没有外键。
CREATE TABLE anime_tracking (
    id         bigint       GENERATED BY DEFAULT AS IDENTITY,
    user_id    bigint       NOT NULL,
    subject_id integer      NOT NULL,
    status     varchar(20)  NOT NULL,
    progress   integer      NOT NULL,
    score      integer,
    notes      text,
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT pk_anime_tracking PRIMARY KEY (id),
    CONSTRAINT fk_anime_tracking_user FOREIGN KEY (user_id) REFERENCES "user" (id)
);

-- 看过的剧集（打勾）
CREATE TABLE episode_watched (
    id          bigint       GENERATED BY DEFAULT AS IDENTITY,
    user_id     bigint       NOT NULL,
    anime_id    integer      NOT NULL,
    episode_num integer      NOT NULL,
    watched_at  timestamp(6),
    CONSTRAINT pk_episode_watched PRIMARY KEY (id),
    CONSTRAINT fk_episode_watched_user FOREIGN KEY (user_id) REFERENCES "user" (id)
);

-- 短评。subject_id 同样指向 Bangumi。
CREATE TABLE review (
    id         bigint       GENERATED BY DEFAULT AS IDENTITY,
    user_id    bigint       NOT NULL,
    subject_id integer      NOT NULL,
    rating     integer      NOT NULL,
    content    text,
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT pk_review PRIMARY KEY (id),
    CONSTRAINT fk_review_user FOREIGN KEY (user_id) REFERENCES "user" (id)
);

-- AI 助手的会话与消息
CREATE TABLE agent_conversation (
    id            bigint       GENERATED BY DEFAULT AS IDENTITY,
    user_id       bigint       NOT NULL,
    title         varchar(60),
    persona       varchar(32)  NOT NULL,
    message_count integer      NOT NULL,
    created_at    timestamp(6),
    updated_at    timestamp(6),
    CONSTRAINT pk_agent_conversation PRIMARY KEY (id),
    CONSTRAINT fk_agent_conversation_user FOREIGN KEY (user_id) REFERENCES "user" (id)
);

CREATE TABLE agent_message (
    id              bigint       GENERATED BY DEFAULT AS IDENTITY,
    conversation_id bigint       NOT NULL,
    role            varchar(16)  NOT NULL,
    content         text,
    created_at      timestamp(6),
    CONSTRAINT pk_agent_message PRIMARY KEY (id),
    CONSTRAINT fk_agent_message_conversation FOREIGN KEY (conversation_id) REFERENCES agent_conversation (id)
);
