-- ============================================================================
--  AniTrack · V7 给短评加「点赞」（PostgreSQL）
--
--  背景：评论贴出去就只能被看见，不能被回应 —— 没有赞，也没有回复。这一版先做赞，
--  回复是 V8。改前 Review 实体里只有评分、正文、两个时间戳（见 Review.java），
--  详情页上的每一条评论都是死的。
--
--  为什么是两张东西（review 加一列 like_count + 一张 review_like）：
--
--  · 只留 review_like 的话，列表里每条评论的赞数要么靠一条 LEFT JOIN + GROUP BY，
--    要么每条一次 COUNT。前者要和「JOIN FETCH r.user + Pageable」共存，而那个组合
--    正是「能跑、能返回、第 2 页是错的」这类 bug 的栖息地（顺序键一变，分页就漏行）；
--    后者是标准的 N+1 —— 20 条评论 20 次查询。
--  · 只留 like_count 一列的话，「我赞过没有」和「谁赞了」这两件事都答不上来。
--
--  代价是计数可能与行数漂移。防法是让 like_count 只有**一个**写入路径：JPQL 的
--  UPDATE（ReviewRepository.increment/decrementLikeCount），JPA 那一侧连碰都碰不到
--  （Review.likeCount 标了 insertable=false, updatable=false —— 否则 Hibernate 的
--  默认 UPDATE 会把这个计数当成普通字段写回去，"改评论正文"就会把并发落地的赞抹掉）。
--  另有一条对账用例钉住「连点 like→unlike→like 之后，like_count 恰好等于
--  review_like 的行数」。
--
--  为什么 review_like 上不建索引：唯一约束 uk_review_like_review_user
--  (review_id, user_id) 自带一棵树，最左前缀 review_id 同时服务两条查询 ——
--  「谁赞了这条」（WHERE review_id = ?）与批量的「我赞过这一页里的哪些」
--  （WHERE user_id = ? AND review_id IN (...)，按 IN 里的每个 id 探针）。
--  再建一个 (user_id) 是纯粹的写放大，理由与 V4 末尾「故意没建的两条」同源；
--  这也让 V4 那条「review 表上恰好只有 IDX_REVIEW_SUBJECT_CREATED」的断言原样成立。
--
--  为什么外键上的 ON DELETE CASCADE 只给 review_id、不给 user_id：
--
--  · review_id 必须级联。删评论有三条路径 —— ReviewService.deleteReview、
--    AdminService.deleteAnyReview、以及测试里的裸 DELETE FROM review —— 不级联的话
--    每一条都会撞外键约束（默认是 RESTRICT）而失败，等于把「删除评论」直接弄坏。
--  · user_id 不能级联。用户目前没有删除路径；将来有了的时候，库级联会静默删掉
--    点赞行而 like_count 不跟着减，计数从此对不上，且没有任何东西会报错。
--    要删用户就得走代码，让计数一起减。
--
--  （这是全仓第一处 ON DELETE CASCADE。V1 建表时一处都没用，是为了让「删父行会带走
--   子行」永远是代码显式做的。这里破例，是因为删除路径有三条、将来可能更多，
--   靠每一条都记得手写 deleteByReviewId 是迟早会漏的；而漏掉的表现是删除功能报错，
--   不是静默错数据。）
--
--  为什么写 IF NOT EXISTS：这份脚本在一台「Flyway 之前就存在的老库」上也会被执行到
--  （那种库被 baseline 到 1，然后从 V2 起逐个补跑，见 application.yml 里 baseline 那段的
--  注释），而它可能因为历史上手工建过这一列或这张表而已经存在。没有 IF NOT EXISTS，
--  那次启动会直接以 "Duplicate column name" / "Table already exists" 失败。
--  在 PG 上另有一样好处：ADD COLUMN ... NOT NULL DEFAULT 0 从 PG 11 起不重写整张表，
--  但手工执行过一半、重跑一次也不会因为列已存在而中断。
--
--  为什么新开 V7 而不是改 V1：V1~V6 已在开发库和线上执行过，Flyway 记着校验和 ——
--  改动已执行脚本的任何一个字节，下次启动都会以 "Migration checksum mismatch for
--  migration version 1" 拒绝启动，唯一的修法是手工去改 flyway_schema_history 表。
--  已经跑过的迁移是历史，只能往后加。
--
--  为什么这次两份脚本逐字相同：ALTER TABLE ... ADD COLUMN IF NOT EXISTS、
--  CREATE TABLE IF NOT EXISTS，以及在列定义里写 GENERATED BY DEFAULT AS IDENTITY 与
--  ON DELETE CASCADE，都是 PostgreSQL（生产用 16）与 H2 2.2 都认的写法，没有方言差异要绕
--  —— 与 V6 同一判断。V3 那边不能这么省事，是因为 PG 的 ALTER TABLE ... ADD CONSTRAINT
--  不支持 IF NOT EXISTS，只能套匿名块自己判断。
--
--  建表本身不锁已有的热路径（review_like 是新表，review 上只是加一列且带默认值）。
--
--  与 h2/V7__add_review_likes.sql 一一对应（语句逐字相同，用例守着这一点）。
-- ============================================================================

ALTER TABLE review ADD COLUMN IF NOT EXISTS like_count BIGINT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS review_like (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    review_id  BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    CONSTRAINT pk_review_like PRIMARY KEY (id),
    CONSTRAINT uk_review_like_review_user UNIQUE (review_id, user_id),
    CONSTRAINT fk_review_like_review FOREIGN KEY (review_id) REFERENCES review (id) ON DELETE CASCADE,
    CONSTRAINT fk_review_like_user FOREIGN KEY (user_id) REFERENCES "user" (id)
);
