-- ============================================================================
--  AniTrack · V9 管理端操作账本（PostgreSQL）
--
--  背景、以及「为什么一张通用表」「为什么一个外键都不挂」「为什么 actor_name 是快照」
--  「为什么只建 created_at 一棵索引」这四件事的理由，逐条写在
--  h2/V9__add_admin_action_log.sql 的头部注释里，这里不重复一遍 —— 两份脚本的
--  **语句**必须逐字相同，注释各写各的（同 V4/V5/V7/V8）。
--
--  这一版没有任何方言特有的写法：CREATE TABLE IF NOT EXISTS、CREATE INDEX IF NOT
--  EXISTS、GENERATED BY DEFAULT AS IDENTITY、TIMESTAMP(6) 在 H2 2.2 与 PostgreSQL 16
--  上都成立，所以两份脚本的语句能保持逐字一致 —— 这条不变量由
--  AdminActionLogMigrationTest.bothDialectsRunTheSameStatements 守着。
-- ============================================================================

CREATE TABLE IF NOT EXISTS admin_action_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    actor_id    BIGINT      NOT NULL,
    actor_name  VARCHAR(50) NOT NULL,
    action      VARCHAR(32) NOT NULL,
    target_type VARCHAR(16) NOT NULL,
    target_id   BIGINT      NOT NULL,
    detail      VARCHAR,
    created_at  TIMESTAMP(6),
    CONSTRAINT pk_admin_action_log PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_admin_action_log_created
    ON admin_action_log (created_at);
